-- @ignore_error
DROP TABLE EXAMPLE CASCADE CONSTRAINT;

CREATE TABLE EXAMPLE (
		ID NUMBER(19) NOT NULL,
		EXAMPLE_NAME VARCHAR2(200) NOT NULL,
		DATA VARCHAR2(4000) NOT NULL
	);

CREATE SEQUENCE SEQ_EXAMPLE_PK
START WITH 1
INCREMENT BY 1
NOCYCLE;


ALTER TABLE EXAMPLE ADD CONSTRAINT PK_EXAMPLE PRIMARY KEY (ID);